/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.652.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plaid.client.model.BeaconMatchSummaryCode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Analysis of whether this account matched between the originally reported Beacon User and the Beacon User that the report syndicated to.
 */
@ApiModel(description = "Analysis of whether this account matched between the originally reported Beacon User and the Beacon User that the report syndicated to.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-21T23:25:15.515981Z[Etc/UTC]")
public class BeaconSyndicatedReportDepositoryAccountMatchAnalysis {
  public static final String SERIALIZED_NAME_ACCOUNT_MASK = "account_mask";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_MASK)
  private String accountMask;

  public static final String SERIALIZED_NAME_ROUTING_NUMBER = "routing_number";
  @SerializedName(SERIALIZED_NAME_ROUTING_NUMBER)
  private String routingNumber;

  public static final String SERIALIZED_NAME_MATCH_STATUS = "match_status";
  @SerializedName(SERIALIZED_NAME_MATCH_STATUS)
  private BeaconMatchSummaryCode matchStatus;


  public BeaconSyndicatedReportDepositoryAccountMatchAnalysis accountMask(String accountMask) {
    
    this.accountMask = accountMask;
    return this;
  }

   /**
   * The last 2-4 numeric characters of this account’s account number.
   * @return accountMask
  **/
  @ApiModelProperty(example = "4000", required = true, value = "The last 2-4 numeric characters of this account’s account number.")

  public String getAccountMask() {
    return accountMask;
  }


  public void setAccountMask(String accountMask) {
    this.accountMask = accountMask;
  }


  public BeaconSyndicatedReportDepositoryAccountMatchAnalysis routingNumber(String routingNumber) {
    
    this.routingNumber = routingNumber;
    return this;
  }

   /**
   * The routing number of the account.
   * @return routingNumber
  **/
  @ApiModelProperty(example = "021000021", required = true, value = "The routing number of the account.")

  public String getRoutingNumber() {
    return routingNumber;
  }


  public void setRoutingNumber(String routingNumber) {
    this.routingNumber = routingNumber;
  }


  public BeaconSyndicatedReportDepositoryAccountMatchAnalysis matchStatus(BeaconMatchSummaryCode matchStatus) {
    
    this.matchStatus = matchStatus;
    return this;
  }

   /**
   * Get matchStatus
   * @return matchStatus
  **/
  @ApiModelProperty(required = true, value = "")

  public BeaconMatchSummaryCode getMatchStatus() {
    return matchStatus;
  }


  public void setMatchStatus(BeaconMatchSummaryCode matchStatus) {
    this.matchStatus = matchStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeaconSyndicatedReportDepositoryAccountMatchAnalysis beaconSyndicatedReportDepositoryAccountMatchAnalysis = (BeaconSyndicatedReportDepositoryAccountMatchAnalysis) o;
    return Objects.equals(this.accountMask, beaconSyndicatedReportDepositoryAccountMatchAnalysis.accountMask) &&
        Objects.equals(this.routingNumber, beaconSyndicatedReportDepositoryAccountMatchAnalysis.routingNumber) &&
        Objects.equals(this.matchStatus, beaconSyndicatedReportDepositoryAccountMatchAnalysis.matchStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountMask, routingNumber, matchStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeaconSyndicatedReportDepositoryAccountMatchAnalysis {\n");
    sb.append("    accountMask: ").append(toIndentedString(accountMask)).append("\n");
    sb.append("    routingNumber: ").append(toIndentedString(routingNumber)).append("\n");
    sb.append("    matchStatus: ").append(toIndentedString(matchStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

