/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.740.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plaid.client.model.BetaIssuesV1Issue;
import com.plaid.client.model.BetaIssuesV1IssueAttribution;
import com.plaid.client.model.BetaIssuesV1IssueBehavior;
import com.plaid.client.model.BetaIssuesV1IssueImpact;
import com.plaid.client.model.BetaIssuesV1IssueResolutionEvent;
import com.plaid.client.model.BetaIssuesV1IssueSeverity;
import com.plaid.client.model.BetaIssuesV1IssueStatus;
import com.plaid.client.model.BetaIssuesV1IssueType;
import com.plaid.client.model.PaymentInitiationRecipientGetResponseAllOf;
import com.plaid.client.model.Products;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * BetaIssuesV1GetResponse defines the response schema for &#x60;/beta/issues/v1/get&#x60;.
 */
@ApiModel(description = "BetaIssuesV1GetResponse defines the response schema for `/beta/issues/v1/get`.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-01T19:02:01.571057Z[Etc/UTC]")
public class BetaIssuesV1GetResponse {
  public static final String SERIALIZED_NAME_ISSUE_ID = "issue_id";
  @SerializedName(SERIALIZED_NAME_ISSUE_ID)
  private String issueId;

  public static final String SERIALIZED_NAME_ISSUE_TYPE = "issue_type";
  @SerializedName(SERIALIZED_NAME_ISSUE_TYPE)
  private BetaIssuesV1IssueType issueType;

  public static final String SERIALIZED_NAME_SEVERITY = "severity";
  @SerializedName(SERIALIZED_NAME_SEVERITY)
  private BetaIssuesV1IssueSeverity severity;

  public static final String SERIALIZED_NAME_INSTITUTION_ID = "institution_id";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_ID)
  private String institutionId;

  public static final String SERIALIZED_NAME_INSTITUTION_NAME = "institution_name";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_NAME)
  private String institutionName;

  public static final String SERIALIZED_NAME_BEHAVIORS = "behaviors";
  @SerializedName(SERIALIZED_NAME_BEHAVIORS)
  private List<BetaIssuesV1IssueBehavior> behaviors = new ArrayList<>();

  public static final String SERIALIZED_NAME_ISSUE_ERROR_TYPE = "issue_error_type";
  @SerializedName(SERIALIZED_NAME_ISSUE_ERROR_TYPE)
  private String issueErrorType;

  public static final String SERIALIZED_NAME_ISSUE_ERROR_CODE = "issue_error_code";
  @SerializedName(SERIALIZED_NAME_ISSUE_ERROR_CODE)
  private String issueErrorCode;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ATTRIBUTION = "attribution";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTION)
  private BetaIssuesV1IssueAttribution attribution;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private BetaIssuesV1IssueStatus status;

  public static final String SERIALIZED_NAME_USER_GUIDANCE = "user_guidance";
  @SerializedName(SERIALIZED_NAME_USER_GUIDANCE)
  private String userGuidance;

  public static final String SERIALIZED_NAME_ESTIMATED_RESOLUTION_TIME = "estimated_resolution_time";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_RESOLUTION_TIME)
  private OffsetDateTime estimatedResolutionTime;

  public static final String SERIALIZED_NAME_START_TIME = "start_time";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  private OffsetDateTime startTime;

  public static final String SERIALIZED_NAME_END_TIME = "end_time";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  private OffsetDateTime endTime;

  public static final String SERIALIZED_NAME_IMPACT = "impact";
  @SerializedName(SERIALIZED_NAME_IMPACT)
  private BetaIssuesV1IssueImpact impact;

  public static final String SERIALIZED_NAME_AFFECTED_PRODUCTS = "affected_products";
  @SerializedName(SERIALIZED_NAME_AFFECTED_PRODUCTS)
  private List<Products> affectedProducts = new ArrayList<>();

  public static final String SERIALIZED_NAME_RESOLUTION_LOG = "resolution_log";
  @SerializedName(SERIALIZED_NAME_RESOLUTION_LOG)
  private List<BetaIssuesV1IssueResolutionEvent> resolutionLog = new ArrayList<>();

  public static final String SERIALIZED_NAME_REQUEST_ID = "request_id";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  private String requestId;


  public BetaIssuesV1GetResponse issueId(String issueId) {
    
    this.issueId = issueId;
    return this;
  }

   /**
   * The customer-visible identifier of the issue.
   * @return issueId
  **/
  @ApiModelProperty(required = true, value = "The customer-visible identifier of the issue.")

  public String getIssueId() {
    return issueId;
  }


  public void setIssueId(String issueId) {
    this.issueId = issueId;
  }


  public BetaIssuesV1GetResponse issueType(BetaIssuesV1IssueType issueType) {
    
    this.issueType = issueType;
    return this;
  }

   /**
   * Get issueType
   * @return issueType
  **/
  @ApiModelProperty(required = true, value = "")

  public BetaIssuesV1IssueType getIssueType() {
    return issueType;
  }


  public void setIssueType(BetaIssuesV1IssueType issueType) {
    this.issueType = issueType;
  }


  public BetaIssuesV1GetResponse severity(BetaIssuesV1IssueSeverity severity) {
    
    this.severity = severity;
    return this;
  }

   /**
   * Get severity
   * @return severity
  **/
  @ApiModelProperty(required = true, value = "")

  public BetaIssuesV1IssueSeverity getSeverity() {
    return severity;
  }


  public void setSeverity(BetaIssuesV1IssueSeverity severity) {
    this.severity = severity;
  }


  public BetaIssuesV1GetResponse institutionId(String institutionId) {
    
    this.institutionId = institutionId;
    return this;
  }

   /**
   * The identifier of the institution affected by the issue.
   * @return institutionId
  **/
  @ApiModelProperty(required = true, value = "The identifier of the institution affected by the issue.")

  public String getInstitutionId() {
    return institutionId;
  }


  public void setInstitutionId(String institutionId) {
    this.institutionId = institutionId;
  }


  public BetaIssuesV1GetResponse institutionName(String institutionName) {
    
    this.institutionName = institutionName;
    return this;
  }

   /**
   * The name of the institution affected by the issue.
   * @return institutionName
  **/
  @ApiModelProperty(required = true, value = "The name of the institution affected by the issue.")

  public String getInstitutionName() {
    return institutionName;
  }


  public void setInstitutionName(String institutionName) {
    this.institutionName = institutionName;
  }


  public BetaIssuesV1GetResponse behaviors(List<BetaIssuesV1IssueBehavior> behaviors) {
    
    this.behaviors = behaviors;
    return this;
  }

  public BetaIssuesV1GetResponse addBehaviorsItem(BetaIssuesV1IssueBehavior behaviorsItem) {
    this.behaviors.add(behaviorsItem);
    return this;
  }

   /**
   * The customer-visible effects of the issue.
   * @return behaviors
  **/
  @ApiModelProperty(required = true, value = "The customer-visible effects of the issue.")

  public List<BetaIssuesV1IssueBehavior> getBehaviors() {
    return behaviors;
  }


  public void setBehaviors(List<BetaIssuesV1IssueBehavior> behaviors) {
    this.behaviors = behaviors;
  }


  public BetaIssuesV1GetResponse issueErrorType(String issueErrorType) {
    
    this.issueErrorType = issueErrorType;
    return this;
  }

   /**
   * The API error type associated with the issue if available. Mirrors the &#x60;error_type&#x60; field on &#x60;PlaidError&#x60; returned on error responses and is safe for programmatic use. Always null or non-null together with &#x60;issue_error_code&#x60;.
   * @return issueErrorType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "INSTITUTION_ERROR", required = true, value = "The API error type associated with the issue if available. Mirrors the `error_type` field on `PlaidError` returned on error responses and is safe for programmatic use. Always null or non-null together with `issue_error_code`.")

  public String getIssueErrorType() {
    return issueErrorType;
  }


  public void setIssueErrorType(String issueErrorType) {
    this.issueErrorType = issueErrorType;
  }


  public BetaIssuesV1GetResponse issueErrorCode(String issueErrorCode) {
    
    this.issueErrorCode = issueErrorCode;
    return this;
  }

   /**
   * The API error code associated with the issue if available. Always null or non-null together with &#x60;issue_error_type&#x60;.
   * @return issueErrorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "INSTITUTION_NOT_RESPONDING", required = true, value = "The API error code associated with the issue if available. Always null or non-null together with `issue_error_type`.")

  public String getIssueErrorCode() {
    return issueErrorCode;
  }


  public void setIssueErrorCode(String issueErrorCode) {
    this.issueErrorCode = issueErrorCode;
  }


  public BetaIssuesV1GetResponse description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A customer-facing explanation of the issue.
   * @return description
  **/
  @ApiModelProperty(required = true, value = "A customer-facing explanation of the issue.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public BetaIssuesV1GetResponse attribution(BetaIssuesV1IssueAttribution attribution) {
    
    this.attribution = attribution;
    return this;
  }

   /**
   * Get attribution
   * @return attribution
  **/
  @ApiModelProperty(required = true, value = "")

  public BetaIssuesV1IssueAttribution getAttribution() {
    return attribution;
  }


  public void setAttribution(BetaIssuesV1IssueAttribution attribution) {
    this.attribution = attribution;
  }


  public BetaIssuesV1GetResponse status(BetaIssuesV1IssueStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")

  public BetaIssuesV1IssueStatus getStatus() {
    return status;
  }


  public void setStatus(BetaIssuesV1IssueStatus status) {
    this.status = status;
  }


  public BetaIssuesV1GetResponse userGuidance(String userGuidance) {
    
    this.userGuidance = userGuidance;
    return this;
  }

   /**
   * Guidance for an end user affected by the issue, or null when no guidance is available.
   * @return userGuidance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "Guidance for an end user affected by the issue, or null when no guidance is available.")

  public String getUserGuidance() {
    return userGuidance;
  }


  public void setUserGuidance(String userGuidance) {
    this.userGuidance = userGuidance;
  }


  public BetaIssuesV1GetResponse estimatedResolutionTime(OffsetDateTime estimatedResolutionTime) {
    
    this.estimatedResolutionTime = estimatedResolutionTime;
    return this;
  }

   /**
   * The estimated resolution time, or null when no estimate is available.
   * @return estimatedResolutionTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The estimated resolution time, or null when no estimate is available.")

  public OffsetDateTime getEstimatedResolutionTime() {
    return estimatedResolutionTime;
  }


  public void setEstimatedResolutionTime(OffsetDateTime estimatedResolutionTime) {
    this.estimatedResolutionTime = estimatedResolutionTime;
  }


  public BetaIssuesV1GetResponse startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * The time the issue began, or null when it is unknown. Only populated for incidents.
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The time the issue began, or null when it is unknown. Only populated for incidents.")

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public BetaIssuesV1GetResponse endTime(OffsetDateTime endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * The time the issue ended, or null while it remains active.
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The time the issue ended, or null while it remains active.")

  public OffsetDateTime getEndTime() {
    return endTime;
  }


  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  public BetaIssuesV1GetResponse impact(BetaIssuesV1IssueImpact impact) {
    
    this.impact = impact;
    return this;
  }

   /**
   * Get impact
   * @return impact
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public BetaIssuesV1IssueImpact getImpact() {
    return impact;
  }


  public void setImpact(BetaIssuesV1IssueImpact impact) {
    this.impact = impact;
  }


  public BetaIssuesV1GetResponse affectedProducts(List<Products> affectedProducts) {
    
    this.affectedProducts = affectedProducts;
    return this;
  }

  public BetaIssuesV1GetResponse addAffectedProductsItem(Products affectedProductsItem) {
    this.affectedProducts.add(affectedProductsItem);
    return this;
  }

   /**
   * The Plaid products affected by the issue.
   * @return affectedProducts
  **/
  @ApiModelProperty(required = true, value = "The Plaid products affected by the issue.")

  public List<Products> getAffectedProducts() {
    return affectedProducts;
  }


  public void setAffectedProducts(List<Products> affectedProducts) {
    this.affectedProducts = affectedProducts;
  }


  public BetaIssuesV1GetResponse resolutionLog(List<BetaIssuesV1IssueResolutionEvent> resolutionLog) {
    
    this.resolutionLog = resolutionLog;
    return this;
  }

  public BetaIssuesV1GetResponse addResolutionLogItem(BetaIssuesV1IssueResolutionEvent resolutionLogItem) {
    this.resolutionLog.add(resolutionLogItem);
    return this;
  }

   /**
   * Resolution events recorded for the issue.
   * @return resolutionLog
  **/
  @ApiModelProperty(required = true, value = "Resolution events recorded for the issue.")

  public List<BetaIssuesV1IssueResolutionEvent> getResolutionLog() {
    return resolutionLog;
  }


  public void setResolutionLog(List<BetaIssuesV1IssueResolutionEvent> resolutionLog) {
    this.resolutionLog = resolutionLog;
  }


  public BetaIssuesV1GetResponse requestId(String requestId) {
    
    this.requestId = requestId;
    return this;
  }

   /**
   * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
   * @return requestId
  **/
  @ApiModelProperty(required = true, value = "A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

  public String getRequestId() {
    return requestId;
  }


  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BetaIssuesV1GetResponse betaIssuesV1GetResponse = (BetaIssuesV1GetResponse) o;
    return Objects.equals(this.issueId, betaIssuesV1GetResponse.issueId) &&
        Objects.equals(this.issueType, betaIssuesV1GetResponse.issueType) &&
        Objects.equals(this.severity, betaIssuesV1GetResponse.severity) &&
        Objects.equals(this.institutionId, betaIssuesV1GetResponse.institutionId) &&
        Objects.equals(this.institutionName, betaIssuesV1GetResponse.institutionName) &&
        Objects.equals(this.behaviors, betaIssuesV1GetResponse.behaviors) &&
        Objects.equals(this.issueErrorType, betaIssuesV1GetResponse.issueErrorType) &&
        Objects.equals(this.issueErrorCode, betaIssuesV1GetResponse.issueErrorCode) &&
        Objects.equals(this.description, betaIssuesV1GetResponse.description) &&
        Objects.equals(this.attribution, betaIssuesV1GetResponse.attribution) &&
        Objects.equals(this.status, betaIssuesV1GetResponse.status) &&
        Objects.equals(this.userGuidance, betaIssuesV1GetResponse.userGuidance) &&
        Objects.equals(this.estimatedResolutionTime, betaIssuesV1GetResponse.estimatedResolutionTime) &&
        Objects.equals(this.startTime, betaIssuesV1GetResponse.startTime) &&
        Objects.equals(this.endTime, betaIssuesV1GetResponse.endTime) &&
        Objects.equals(this.impact, betaIssuesV1GetResponse.impact) &&
        Objects.equals(this.affectedProducts, betaIssuesV1GetResponse.affectedProducts) &&
        Objects.equals(this.resolutionLog, betaIssuesV1GetResponse.resolutionLog) &&
        Objects.equals(this.requestId, betaIssuesV1GetResponse.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueId, issueType, severity, institutionId, institutionName, behaviors, issueErrorType, issueErrorCode, description, attribution, status, userGuidance, estimatedResolutionTime, startTime, endTime, impact, affectedProducts, resolutionLog, requestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BetaIssuesV1GetResponse {\n");
    sb.append("    issueId: ").append(toIndentedString(issueId)).append("\n");
    sb.append("    issueType: ").append(toIndentedString(issueType)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    institutionId: ").append(toIndentedString(institutionId)).append("\n");
    sb.append("    institutionName: ").append(toIndentedString(institutionName)).append("\n");
    sb.append("    behaviors: ").append(toIndentedString(behaviors)).append("\n");
    sb.append("    issueErrorType: ").append(toIndentedString(issueErrorType)).append("\n");
    sb.append("    issueErrorCode: ").append(toIndentedString(issueErrorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    attribution: ").append(toIndentedString(attribution)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userGuidance: ").append(toIndentedString(userGuidance)).append("\n");
    sb.append("    estimatedResolutionTime: ").append(toIndentedString(estimatedResolutionTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    impact: ").append(toIndentedString(impact)).append("\n");
    sb.append("    affectedProducts: ").append(toIndentedString(affectedProducts)).append("\n");
    sb.append("    resolutionLog: ").append(toIndentedString(resolutionLog)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

