/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.686.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status of the digital presence check
 */
@JsonAdapter(BusinessVerificationStatusWebPresenceCheck.Adapter.class)
public enum BusinessVerificationStatusWebPresenceCheck {
  
  ACTIVE("active"),
  
  SUCCESS("success"),
  
  FAILED("failed"),
  
  NOT_APPLICABLE("not_applicable"),

  // This is returned when an enum is returned from the API that doesn't exist in the OpenAPI file.
  // Try upgrading your client-library version.
  ENUM_UNKNOWN("ENUM_UNKNOWN");

  private String value;

  BusinessVerificationStatusWebPresenceCheck(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BusinessVerificationStatusWebPresenceCheck fromValue(String value) {
    for (BusinessVerificationStatusWebPresenceCheck b : BusinessVerificationStatusWebPresenceCheck.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    
    return BusinessVerificationStatusWebPresenceCheck.ENUM_UNKNOWN;
  }

  public static class Adapter extends TypeAdapter<BusinessVerificationStatusWebPresenceCheck> {
    @Override
    public void write(final JsonWriter jsonWriter, final BusinessVerificationStatusWebPresenceCheck enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BusinessVerificationStatusWebPresenceCheck read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return BusinessVerificationStatusWebPresenceCheck.fromValue(value);
    }
  }
}

