/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.673.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An insight that can be detected by the Cash Flow Updates product
 */
@JsonAdapter(CashFlowInsight.Adapter.class)
public enum CashFlowInsight {
  
  LARGE_DEPOSIT_DETECTED("LARGE_DEPOSIT_DETECTED"),
  
  LOW_BALANCE_DETECTED("LOW_BALANCE_DETECTED"),
  
  NEW_LOAN_PAYMENT_DETECTED("NEW_LOAN_PAYMENT_DETECTED"),
  
  NSF_OVERDRAFT_DETECTED("NSF_OVERDRAFT_DETECTED"),

  // This is returned when an enum is returned from the API that doesn't exist in the OpenAPI file.
  // Try upgrading your client-library version.
  ENUM_UNKNOWN("ENUM_UNKNOWN");

  private String value;

  CashFlowInsight(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CashFlowInsight fromValue(String value) {
    for (CashFlowInsight b : CashFlowInsight.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    
    return CashFlowInsight.ENUM_UNKNOWN;
  }

  public static class Adapter extends TypeAdapter<CashFlowInsight> {
    @Override
    public void write(final JsonWriter jsonWriter, final CashFlowInsight enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CashFlowInsight read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CashFlowInsight.fromValue(value);
    }
  }
}

