/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.617.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plaid.client.model.ConsumerReportPermissiblePurpose;
import com.plaid.client.model.CraCheckReportCashflowInsightsGetOptions;
import com.plaid.client.model.CraCheckReportCreateBaseReportOptions;
import com.plaid.client.model.CraCheckReportPartnerInsightsGetOptions;
import com.plaid.client.model.Products;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CraCheckReportCreateRequest defines the request schema for &#x60;/cra/check_report/create&#x60;.
 */
@ApiModel(description = "CraCheckReportCreateRequest defines the request schema for `/cra/check_report/create`.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-07T19:05:33.763924Z[Etc/UTC]")
public class CraCheckReportCreateRequest {
  public static final String SERIALIZED_NAME_CLIENT_ID = "client_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  private String clientId;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private String secret;

  public static final String SERIALIZED_NAME_USER_TOKEN = "user_token";
  @SerializedName(SERIALIZED_NAME_USER_TOKEN)
  private String userToken;

  public static final String SERIALIZED_NAME_WEBHOOK = "webhook";
  @SerializedName(SERIALIZED_NAME_WEBHOOK)
  private String webhook;

  public static final String SERIALIZED_NAME_DAYS_REQUESTED = "days_requested";
  @SerializedName(SERIALIZED_NAME_DAYS_REQUESTED)
  private Integer daysRequested;

  public static final String SERIALIZED_NAME_DAYS_REQUIRED = "days_required";
  @SerializedName(SERIALIZED_NAME_DAYS_REQUIRED)
  private Integer daysRequired;

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  private List<Products> products = null;

  public static final String SERIALIZED_NAME_BASE_REPORT = "base_report";
  @SerializedName(SERIALIZED_NAME_BASE_REPORT)
  private CraCheckReportCreateBaseReportOptions baseReport;

  public static final String SERIALIZED_NAME_CASHFLOW_INSIGHTS = "cashflow_insights";
  @SerializedName(SERIALIZED_NAME_CASHFLOW_INSIGHTS)
  private CraCheckReportCashflowInsightsGetOptions cashflowInsights;

  public static final String SERIALIZED_NAME_PARTNER_INSIGHTS = "partner_insights";
  @SerializedName(SERIALIZED_NAME_PARTNER_INSIGHTS)
  private CraCheckReportPartnerInsightsGetOptions partnerInsights;

  public static final String SERIALIZED_NAME_CONSUMER_REPORT_PERMISSIBLE_PURPOSE = "consumer_report_permissible_purpose";
  @SerializedName(SERIALIZED_NAME_CONSUMER_REPORT_PERMISSIBLE_PURPOSE)
  private ConsumerReportPermissiblePurpose consumerReportPermissiblePurpose;


  public CraCheckReportCreateRequest clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

   /**
   * Your Plaid API &#x60;client_id&#x60;. The &#x60;client_id&#x60; is required and may be provided either in the &#x60;PLAID-CLIENT-ID&#x60; header or as part of a request body.
   * @return clientId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.")

  public String getClientId() {
    return clientId;
  }


  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  public CraCheckReportCreateRequest secret(String secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Your Plaid API &#x60;secret&#x60;. The &#x60;secret&#x60; is required and may be provided either in the &#x60;PLAID-SECRET&#x60; header or as part of a request body.
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.")

  public String getSecret() {
    return secret;
  }


  public void setSecret(String secret) {
    this.secret = secret;
  }


  public CraCheckReportCreateRequest userToken(String userToken) {
    
    this.userToken = userToken;
    return this;
  }

   /**
   * The user token associated with the User data is being requested for.
   * @return userToken
  **/
  @ApiModelProperty(required = true, value = "The user token associated with the User data is being requested for.")

  public String getUserToken() {
    return userToken;
  }


  public void setUserToken(String userToken) {
    this.userToken = userToken;
  }


  public CraCheckReportCreateRequest webhook(String webhook) {
    
    this.webhook = webhook;
    return this;
  }

   /**
   * The destination URL to which webhooks will be sent 
   * @return webhook
  **/
  @ApiModelProperty(required = true, value = "The destination URL to which webhooks will be sent ")

  public String getWebhook() {
    return webhook;
  }


  public void setWebhook(String webhook) {
    this.webhook = webhook;
  }


  public CraCheckReportCreateRequest daysRequested(Integer daysRequested) {
    
    this.daysRequested = daysRequested;
    return this;
  }

   /**
   * The number of days of data to request for the report. Default value is 365; maximum is 731; minimum is 180. If a value lower than 180 is provided, a minimum of 180 days of history will be requested.
   * maximum: 731
   * @return daysRequested
  **/
  @ApiModelProperty(required = true, value = "The number of days of data to request for the report. Default value is 365; maximum is 731; minimum is 180. If a value lower than 180 is provided, a minimum of 180 days of history will be requested.")

  public Integer getDaysRequested() {
    return daysRequested;
  }


  public void setDaysRequested(Integer daysRequested) {
    this.daysRequested = daysRequested;
  }


  public CraCheckReportCreateRequest daysRequired(Integer daysRequired) {
    
    this.daysRequired = daysRequired;
    return this;
  }

   /**
   * The minimum number of days of data required for the report to be successfully generated.
   * @return daysRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The minimum number of days of data required for the report to be successfully generated.")

  public Integer getDaysRequired() {
    return daysRequired;
  }


  public void setDaysRequired(Integer daysRequired) {
    this.daysRequired = daysRequired;
  }


  public CraCheckReportCreateRequest products(List<Products> products) {
    
    this.products = products;
    return this;
  }

  public CraCheckReportCreateRequest addProductsItem(Products productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Specifies a list of products that will be eagerly generated when creating the report. These products will be made available before a success webhook is sent. Use this option to minimize response latency for product &#x60;/get&#x60; endpoints.
   * @return products
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies a list of products that will be eagerly generated when creating the report. These products will be made available before a success webhook is sent. Use this option to minimize response latency for product `/get` endpoints.")

  public List<Products> getProducts() {
    return products;
  }


  public void setProducts(List<Products> products) {
    this.products = products;
  }


  public CraCheckReportCreateRequest baseReport(CraCheckReportCreateBaseReportOptions baseReport) {
    
    this.baseReport = baseReport;
    return this;
  }

   /**
   * Get baseReport
   * @return baseReport
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CraCheckReportCreateBaseReportOptions getBaseReport() {
    return baseReport;
  }


  public void setBaseReport(CraCheckReportCreateBaseReportOptions baseReport) {
    this.baseReport = baseReport;
  }


  public CraCheckReportCreateRequest cashflowInsights(CraCheckReportCashflowInsightsGetOptions cashflowInsights) {
    
    this.cashflowInsights = cashflowInsights;
    return this;
  }

   /**
   * Get cashflowInsights
   * @return cashflowInsights
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CraCheckReportCashflowInsightsGetOptions getCashflowInsights() {
    return cashflowInsights;
  }


  public void setCashflowInsights(CraCheckReportCashflowInsightsGetOptions cashflowInsights) {
    this.cashflowInsights = cashflowInsights;
  }


  public CraCheckReportCreateRequest partnerInsights(CraCheckReportPartnerInsightsGetOptions partnerInsights) {
    
    this.partnerInsights = partnerInsights;
    return this;
  }

   /**
   * Get partnerInsights
   * @return partnerInsights
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CraCheckReportPartnerInsightsGetOptions getPartnerInsights() {
    return partnerInsights;
  }


  public void setPartnerInsights(CraCheckReportPartnerInsightsGetOptions partnerInsights) {
    this.partnerInsights = partnerInsights;
  }


  public CraCheckReportCreateRequest consumerReportPermissiblePurpose(ConsumerReportPermissiblePurpose consumerReportPermissiblePurpose) {
    
    this.consumerReportPermissiblePurpose = consumerReportPermissiblePurpose;
    return this;
  }

   /**
   * Get consumerReportPermissiblePurpose
   * @return consumerReportPermissiblePurpose
  **/
  @ApiModelProperty(required = true, value = "")

  public ConsumerReportPermissiblePurpose getConsumerReportPermissiblePurpose() {
    return consumerReportPermissiblePurpose;
  }


  public void setConsumerReportPermissiblePurpose(ConsumerReportPermissiblePurpose consumerReportPermissiblePurpose) {
    this.consumerReportPermissiblePurpose = consumerReportPermissiblePurpose;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CraCheckReportCreateRequest craCheckReportCreateRequest = (CraCheckReportCreateRequest) o;
    return Objects.equals(this.clientId, craCheckReportCreateRequest.clientId) &&
        Objects.equals(this.secret, craCheckReportCreateRequest.secret) &&
        Objects.equals(this.userToken, craCheckReportCreateRequest.userToken) &&
        Objects.equals(this.webhook, craCheckReportCreateRequest.webhook) &&
        Objects.equals(this.daysRequested, craCheckReportCreateRequest.daysRequested) &&
        Objects.equals(this.daysRequired, craCheckReportCreateRequest.daysRequired) &&
        Objects.equals(this.products, craCheckReportCreateRequest.products) &&
        Objects.equals(this.baseReport, craCheckReportCreateRequest.baseReport) &&
        Objects.equals(this.cashflowInsights, craCheckReportCreateRequest.cashflowInsights) &&
        Objects.equals(this.partnerInsights, craCheckReportCreateRequest.partnerInsights) &&
        Objects.equals(this.consumerReportPermissiblePurpose, craCheckReportCreateRequest.consumerReportPermissiblePurpose);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, secret, userToken, webhook, daysRequested, daysRequired, products, baseReport, cashflowInsights, partnerInsights, consumerReportPermissiblePurpose);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CraCheckReportCreateRequest {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    userToken: ").append(toIndentedString(userToken)).append("\n");
    sb.append("    webhook: ").append(toIndentedString(webhook)).append("\n");
    sb.append("    daysRequested: ").append(toIndentedString(daysRequested)).append("\n");
    sb.append("    daysRequired: ").append(toIndentedString(daysRequired)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    baseReport: ").append(toIndentedString(baseReport)).append("\n");
    sb.append("    cashflowInsights: ").append(toIndentedString(cashflowInsights)).append("\n");
    sb.append("    partnerInsights: ").append(toIndentedString(partnerInsights)).append("\n");
    sb.append("    consumerReportPermissiblePurpose: ").append(toIndentedString(consumerReportPermissiblePurpose)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

