/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.181.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plaid.client.model.CreditSessionResults;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Metadata and results for a link session
 */
@ApiModel(description = "Metadata and results for a link session")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-20T20:43:44.520784Z[Etc/UTC]")
public class CreditSession {
  public static final String SERIALIZED_NAME_LINK_SESSION_ID = "link_session_id";
  @SerializedName(SERIALIZED_NAME_LINK_SESSION_ID)
  private String linkSessionId;

  public static final String SERIALIZED_NAME_SESSION_START_TIME = "session_start_time";
  @SerializedName(SERIALIZED_NAME_SESSION_START_TIME)
  private OffsetDateTime sessionStartTime;

  public static final String SERIALIZED_NAME_RESULTS = "results";
  @SerializedName(SERIALIZED_NAME_RESULTS)
  private CreditSessionResults results;


  public CreditSession linkSessionId(String linkSessionId) {
    
    this.linkSessionId = linkSessionId;
    return this;
  }

   /**
   * The unique identifier associated with the Link Session.
   * @return linkSessionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique identifier associated with the Link Session.")

  public String getLinkSessionId() {
    return linkSessionId;
  }


  public void setLinkSessionId(String linkSessionId) {
    this.linkSessionId = linkSessionId;
  }


  public CreditSession sessionStartTime(OffsetDateTime sessionStartTime) {
    
    this.sessionStartTime = sessionStartTime;
    return this;
  }

   /**
   * The time when the link session started
   * @return sessionStartTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time when the link session started")

  public OffsetDateTime getSessionStartTime() {
    return sessionStartTime;
  }


  public void setSessionStartTime(OffsetDateTime sessionStartTime) {
    this.sessionStartTime = sessionStartTime;
  }


  public CreditSession results(CreditSessionResults results) {
    
    this.results = results;
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CreditSessionResults getResults() {
    return results;
  }


  public void setResults(CreditSessionResults results) {
    this.results = results;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditSession creditSession = (CreditSession) o;
    return Objects.equals(this.linkSessionId, creditSession.linkSessionId) &&
        Objects.equals(this.sessionStartTime, creditSession.sessionStartTime) &&
        Objects.equals(this.results, creditSession.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkSessionId, sessionStartTime, results);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditSession {\n");
    sb.append("    linkSessionId: ").append(toIndentedString(linkSessionId)).append("\n");
    sb.append("    sessionStartTime: ").append(toIndentedString(sessionStartTime)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

