/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.5.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plaid.client.model.DepositSwitchTargetAccount;
import com.plaid.client.model.DepositSwitchTargetUser;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DepositSwitchAltCreateRequest defines the request schema for &#x60;/deposit_switch/alt/create&#x60;
 */
@ApiModel(description = "DepositSwitchAltCreateRequest defines the request schema for `/deposit_switch/alt/create`")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-18T00:06:17.510Z[GMT]")
public class DepositSwitchAltCreateRequest {
  public static final String SERIALIZED_NAME_CLIENT_ID = "client_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  private String clientId;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private String secret;

  public static final String SERIALIZED_NAME_TARGET_ACCOUNT = "target_account";
  @SerializedName(SERIALIZED_NAME_TARGET_ACCOUNT)
  private DepositSwitchTargetAccount targetAccount;

  public static final String SERIALIZED_NAME_TARGET_USER = "target_user";
  @SerializedName(SERIALIZED_NAME_TARGET_USER)
  private DepositSwitchTargetUser targetUser;


  public DepositSwitchAltCreateRequest clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

   /**
   * Your Plaid API &#x60;client_id&#x60;.
   * @return clientId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Your Plaid API `client_id`.")

  public String getClientId() {
    return clientId;
  }


  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  public DepositSwitchAltCreateRequest secret(String secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Your Plaid API &#x60;secret&#x60;.
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Your Plaid API `secret`.")

  public String getSecret() {
    return secret;
  }


  public void setSecret(String secret) {
    this.secret = secret;
  }


  public DepositSwitchAltCreateRequest targetAccount(DepositSwitchTargetAccount targetAccount) {
    
    this.targetAccount = targetAccount;
    return this;
  }

   /**
   * Get targetAccount
   * @return targetAccount
  **/
  @ApiModelProperty(required = true, value = "")

  public DepositSwitchTargetAccount getTargetAccount() {
    return targetAccount;
  }


  public void setTargetAccount(DepositSwitchTargetAccount targetAccount) {
    this.targetAccount = targetAccount;
  }


  public DepositSwitchAltCreateRequest targetUser(DepositSwitchTargetUser targetUser) {
    
    this.targetUser = targetUser;
    return this;
  }

   /**
   * Get targetUser
   * @return targetUser
  **/
  @ApiModelProperty(required = true, value = "")

  public DepositSwitchTargetUser getTargetUser() {
    return targetUser;
  }


  public void setTargetUser(DepositSwitchTargetUser targetUser) {
    this.targetUser = targetUser;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositSwitchAltCreateRequest depositSwitchAltCreateRequest = (DepositSwitchAltCreateRequest) o;
    return Objects.equals(this.clientId, depositSwitchAltCreateRequest.clientId) &&
        Objects.equals(this.secret, depositSwitchAltCreateRequest.secret) &&
        Objects.equals(this.targetAccount, depositSwitchAltCreateRequest.targetAccount) &&
        Objects.equals(this.targetUser, depositSwitchAltCreateRequest.targetUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, secret, targetAccount, targetUser);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositSwitchAltCreateRequest {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    targetAccount: ").append(toIndentedString(targetAccount)).append("\n");
    sb.append("    targetUser: ").append(toIndentedString(targetUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

