/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.652.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * How Plaid should deliver the Plaid Link session to the customer. Only available to customers enabled for Link Delivery (beta). To request Link Delivery access, contact your account manager. &#39;sms&#39; will deliver via SMS. Must pass &#x60;user.phone_number&#x60;. &#39;email&#39; will deliver via email. Must pass &#x60;user.email_address&#x60;. In the Sandbox environment, this field will be ignored; use the Production environment to test Link Delivery instead. 
 */
@JsonAdapter(HostedLinkDeliveryMethod.Adapter.class)
public enum HostedLinkDeliveryMethod {
  
  SMS("sms"),
  
  EMAIL("email"),

  // This is returned when an enum is returned from the API that doesn't exist in the OpenAPI file.
  // Try upgrading your client-library version.
  ENUM_UNKNOWN("ENUM_UNKNOWN");

  private String value;

  HostedLinkDeliveryMethod(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static HostedLinkDeliveryMethod fromValue(String value) {
    for (HostedLinkDeliveryMethod b : HostedLinkDeliveryMethod.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    
    return HostedLinkDeliveryMethod.ENUM_UNKNOWN;
  }

  public static class Adapter extends TypeAdapter<HostedLinkDeliveryMethod> {
    @Override
    public void write(final JsonWriter jsonWriter, final HostedLinkDeliveryMethod enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public HostedLinkDeliveryMethod read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return HostedLinkDeliveryMethod.fromValue(value);
    }
  }
}

