/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.658.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plaid.client.model.CashflowAttributesVersion;
import com.plaid.client.model.PlaidCheckScoreVersion;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Specifies options for initializing Link for use with the Cashflow Insights product.
 */
@ApiModel(description = "Specifies options for initializing Link for use with the Cashflow Insights product.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-13T19:24:31.901891Z[Etc/UTC]")
public class LinkTokenCreateRequestCraOptionsCashflowInsights {
  public static final String SERIALIZED_NAME_PLAID_CHECK_SCORE_VERSION = "plaid_check_score_version";
  @SerializedName(SERIALIZED_NAME_PLAID_CHECK_SCORE_VERSION)
  private PlaidCheckScoreVersion plaidCheckScoreVersion;

  public static final String SERIALIZED_NAME_ATTRIBUTES_VERSION = "attributes_version";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES_VERSION)
  private CashflowAttributesVersion attributesVersion;


  public LinkTokenCreateRequestCraOptionsCashflowInsights plaidCheckScoreVersion(PlaidCheckScoreVersion plaidCheckScoreVersion) {
    
    this.plaidCheckScoreVersion = plaidCheckScoreVersion;
    return this;
  }

   /**
   * Get plaidCheckScoreVersion
   * @return plaidCheckScoreVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PlaidCheckScoreVersion getPlaidCheckScoreVersion() {
    return plaidCheckScoreVersion;
  }


  public void setPlaidCheckScoreVersion(PlaidCheckScoreVersion plaidCheckScoreVersion) {
    this.plaidCheckScoreVersion = plaidCheckScoreVersion;
  }


  public LinkTokenCreateRequestCraOptionsCashflowInsights attributesVersion(CashflowAttributesVersion attributesVersion) {
    
    this.attributesVersion = attributesVersion;
    return this;
  }

   /**
   * Get attributesVersion
   * @return attributesVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CashflowAttributesVersion getAttributesVersion() {
    return attributesVersion;
  }


  public void setAttributesVersion(CashflowAttributesVersion attributesVersion) {
    this.attributesVersion = attributesVersion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkTokenCreateRequestCraOptionsCashflowInsights linkTokenCreateRequestCraOptionsCashflowInsights = (LinkTokenCreateRequestCraOptionsCashflowInsights) o;
    return Objects.equals(this.plaidCheckScoreVersion, linkTokenCreateRequestCraOptionsCashflowInsights.plaidCheckScoreVersion) &&
        Objects.equals(this.attributesVersion, linkTokenCreateRequestCraOptionsCashflowInsights.attributesVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plaidCheckScoreVersion, attributesVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkTokenCreateRequestCraOptionsCashflowInsights {\n");
    sb.append("    plaidCheckScoreVersion: ").append(toIndentedString(plaidCheckScoreVersion)).append("\n");
    sb.append("    attributesVersion: ").append(toIndentedString(attributesVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

