/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.503.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TransactionsRecurringMergeInput defines a single input to the &#x60;/transactions/recurring/streams/merge&#x60; endpoint.
 */
@ApiModel(description = "TransactionsRecurringMergeInput defines a single input to the `/transactions/recurring/streams/merge` endpoint.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-28T21:00:55.745394Z[Etc/UTC]")
public class TransactionsRecurringMergeInput {
  public static final String SERIALIZED_NAME_STREAM_IDS = "stream_ids";
  @SerializedName(SERIALIZED_NAME_STREAM_IDS)
  private List<String> streamIds = new ArrayList<>();


  public TransactionsRecurringMergeInput streamIds(List<String> streamIds) {
    
    this.streamIds = streamIds;
    return this;
  }

  public TransactionsRecurringMergeInput addStreamIdsItem(String streamIdsItem) {
    this.streamIds.add(streamIdsItem);
    return this;
  }

   /**
   * IDs of all the streams that will be merged into the first stream. This operation will retain the stream_id of the first stream.
   * @return streamIds
  **/
  @ApiModelProperty(required = true, value = "IDs of all the streams that will be merged into the first stream. This operation will retain the stream_id of the first stream.")

  public List<String> getStreamIds() {
    return streamIds;
  }


  public void setStreamIds(List<String> streamIds) {
    this.streamIds = streamIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionsRecurringMergeInput transactionsRecurringMergeInput = (TransactionsRecurringMergeInput) o;
    return Objects.equals(this.streamIds, transactionsRecurringMergeInput.streamIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(streamIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionsRecurringMergeInput {\n");
    sb.append("    streamIds: ").append(toIndentedString(streamIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

