/*
 * The Plaid API
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.672.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.plaid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plaid.client.model.IdentityCreationResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserUpdateResponse defines the response schema for &#x60;/user/update&#x60;
 */
@ApiModel(description = "UserUpdateResponse defines the response schema for `/user/update`")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-05T10:30:35.648026Z[Etc/UTC]")
public class UserUpdateResponse {
  public static final String SERIALIZED_NAME_REQUEST_ID = "request_id";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  private String requestId;

  public static final String SERIALIZED_NAME_IDENTITY_CREATION_RESULT = "identity_creation_result";
  @SerializedName(SERIALIZED_NAME_IDENTITY_CREATION_RESULT)
  private IdentityCreationResult identityCreationResult;


  public UserUpdateResponse requestId(String requestId) {
    
    this.requestId = requestId;
    return this;
  }

   /**
   * A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
   * @return requestId
  **/
  @ApiModelProperty(required = true, value = "A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.")

  public String getRequestId() {
    return requestId;
  }


  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }


  public UserUpdateResponse identityCreationResult(IdentityCreationResult identityCreationResult) {
    
    this.identityCreationResult = identityCreationResult;
    return this;
  }

   /**
   * Get identityCreationResult
   * @return identityCreationResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IdentityCreationResult getIdentityCreationResult() {
    return identityCreationResult;
  }


  public void setIdentityCreationResult(IdentityCreationResult identityCreationResult) {
    this.identityCreationResult = identityCreationResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUpdateResponse userUpdateResponse = (UserUpdateResponse) o;
    return Objects.equals(this.requestId, userUpdateResponse.requestId) &&
        Objects.equals(this.identityCreationResult, userUpdateResponse.identityCreationResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, identityCreationResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUpdateResponse {\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    identityCreationResult: ").append(toIndentedString(identityCreationResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

